lab3:
	g++ SectionTerm.h -c -std=c++14 
	g++ StudentInstructor.cpp -c -std=c++14
	g++ College.cpp -c -std=c++14
	g++ Analysis.cpp -c -std=c++14
	g++ Read.cpp -c -std=c++14
	g++ Write.cpp -c -std=c++14 
	g++ main.cpp -o main.exe -std=c++14